#!/bin/env sh
# Set the release type (Official or RB)
release=RELEASE
updateurl=UPDATEURL

# Working directory is actually the steam install location, so we need to find the path of this script
tooldir="$(realpath "$(dirname "$0")")"

latest=$(curl -L "updateurl")
current=$(awk 'NR==1 {print; exit}' < "$tooldir/version")
currentrelease=$(awk 'NR==2 {print; exit}' < "$tooldir/version")
if [ "$latest" != "$current" ] && [ "$release" = "$currentrelease" ]; then
    mkdir -p "$tooldir/tmp"
    if [ "$release" = "RB" ]; then
        repo="rankynbass"
    else if [ "$release" = "Official" ]; then
        repo="goatcorp"
    else
        exit 0;
    fi
    curl -L "https://github.com/$repo/XIVLauncher.Core/releases/latest/download/XIVLauncher.Core.tar.gz" -o "$tooldir/tmp/XIVLauncher.Core.tar.gz"
    curl -L "https://github.com/rankynbass/aria2-static-build/releases/latest/download/aria2-static.tar.gz" -o "$tooldir/tmp/aria2-static.tar.gz"
    
fi
