#!/bin/env sh
# Set the release type (Official or RB)
release=RELEASE
updateurl=UPDATEURL
flatpak=FLATPAK

# LD_LIBRARY_PATH will be set by steam to very old ubuntu versions. This will cause curl to fail
# Save the value and unset.
OLD_LLP=$LD_LIBRARY_PATH
unset LD_LIBRARY_PATH

# Working directory is actually the steam install location, so we need to find the path of this script
tooldir="$(realpath "$(dirname "$0")")"
tempdir="$tooldir/tmp"

# Dirty hack to convert a.b.c.d version to a number so it can be compared
VersionToNumber()
{
    if [ -z $1 ]; then
        echo "Error! No version number provided to VersionToNumber()"
        exit 1
    fi
    set -f
    old_IFS=$IFS
    IFS='.'
    read -r FIRST SECOND THIRD FOURTH <<< $1
    expr ${FIRST:-0} '*' 1000000 + ${SECOND:-0} '*' 10000 + ${THIRD:-0} '*' 100 + ${FOURTH:-0}
    IFS=$old_IFS
    set +f
}

# Do a version check to see if we need to update.
VersionCheck() {
    echo "Test script. Automatically downloading..."
    Download
}

# Download the latest XIVLocal-Installer and extract to temp directory, then install
Download() {
    mkdir -p "$tempdir/XIVLocal-Installer"

    cp -r LOCALREPO "$tempdir/XIVLocal-Installer"

    if [ "$flatpak" = "0" ]; then
        if [ "$release" = "RB-Patched" ]; then
            args="--steam --force --RB --test"
        else
            args="--steam --force --test"
        fi
    else
        if [ "$release" = "RB-Patched" ]; then
            args="--steamflatpak --force --RB --test"
        else
            args="--steamflatpak --force --test"
        fi
    fi

    "$tempdir/XIVLocal-Installer/install.sh" $args

    xdg-open "$tooldir/XIVLauncher/updated.txt"
}

VersionCheck

# Set LD_LIBRARY_PATH back
LD_LIBRARY_PATH=$OLD_LLP